### ISSUE TITLE
TeluguOCR + Chamanti OCR

### ISSUE THREAD

**Issue by zuphilip** [kba/awesome-ocr#49]
**Banti Telugu OCR**: https://github.com/TeluguOCR/banti_telugu_ocr
"This framework relies on the ability of a segmentation algorithm to break the text in to glyphs."

**Chamanti OCR**: https://github.com/rakeshvar/chamanti_ocr
"It will not rely on segmentation algorithms (at the glyph level), making it ideal for highly agglutinative scripts like Arabic, Devanagari etc. We will be starting with Telugu however."

It is hard to guess for me, how good the recognition work, because I don't understand Telugu and I haven't found any results, discussions, blog posts (which I can read). But the project looks IMO very promising from a technical point. CC @rakeshvar

**Comment by rakeshvar** [comment]
Here is a paper on banti. http://arxiv.org/abs/1509.05962
I will update it to the latest version soon, that will have comparison with Google's
@chillaranand

**Comment by zuphilip** [comment]
@rakeshvar Thank you for the link to the paper!

Closed by @kba in https://github.com/kba/awesome-ocr/commit/980a9b930f7ef3b7016b6e401c96fb78a91a96a5
