### ISSUE TITLE
ocropus - OCR engine based on CLSTM, Apache 2.0

### ISSUE THREAD

**Issue by amitdo** [kba/awesome-ocr#53]
>[ocropus](https://github.com/tmbdev/ocropy) - OCR engine based on CLSTM, Apache 2.0

It the other way around. 'ocropy' was out before 'clstm' :-)

Maybe the intention was 'LSTM' and not '**C**LSTM'.

Using 'ocropus' and linking to ocropy might confuse anyone that does not know ocropy's history.

**Comment by kba** [comment]
Yeah, that should be just LSTM :) I'll fix it.

**Comment by kba** [comment]
Thanks, corrected, https://github.com/kba/awesome-ocr/commit/46dee07fb56e46dfed3aec5903fde79b8cbba143
