### ISSUE TITLE
Image pre-processing scripts

### ISSUE THREAD

**Issue by DavidUnderdown** [kba/awesome-ocr#71]
There are some nice python scripts for various image pre-processing tasks described at https://mzucker.github.io/ eg "Unprojecting text with ellipses", "Compressing and enhancing hand-written notes", and "Page dewarping".  The blog posts contain links to the scripts themselves in the author's GitHub repository.

**Comment by kba** [comment]
Sounds good, can you add a list item under Blog Posts with links and send a PR?

**Comment by DavidUnderdown** [comment]
Done, pull request #72 created, but I need to tidy up my formatting I now realise.  Haven't quite got the hang of mark down yet, and forgot to press preview, sorry.

**Comment by kba** [comment]
Thanks, #72 merged.
