### ISSUE TITLE
Open Source OCR for Large Collections of Scanned Documents [video]

### ISSUE THREAD

**Issue by cneud** [kba/awesome-ocr#76]
https://www.youtube.com/watch?v=gcjCiS9pJ3A

**Comment by zuphilip** [comment]
This seems to be a duplicate of #34.

**Comment by cneud** [comment]
Oops, sorry, should have had a closer look. Closed.

**Comment by kba** [comment]
We could add those to the README. Maybe:

<details>
  <summary>Open Source OCR for Large Collections of Scanned Documents [video]</summary>
  <a href="https://www.youtube.com/watch?v=gcjCiS9pJ3A"><img src="https://img.youtube.com/vi/gcjCiS9pJ3A/0.jpg"/></a>
</details>
