### ISSUE TITLE
(Open-Source-)OCR-Workflows

### ISSUE THREAD

**Issue by amitdo** [kba/awesome-ocr#82]
Kay-Michael Würzner @wrznr
(Open-Source-)OCR-Workflows
https://edoc.bbaw.de/frontdoor/index/index/docId/2786

I don't know how much awesome is it, since I don't know German :-)

**Comment by kba** [comment]
It's an overview of the state of the art in OCR and related technologies (binarisation, deskewing etc., layout recognition), shows some of the current solutions and a bit on the [OCR-D](github.com/OCR-D) project. 

Also presents the results of merging results of different engines to improve quality (code: https://github.com/wrznr/pyocrd).

**Comment by amitdo** [comment]
Page 40 lInks to this repo, awesome!

**Comment by amitdo** [comment]
Your link is broken.

http://ocr-d.de/
I used Google translate to browse this site.
