### ISSUE TITLE
Add category for ground truth

### ISSUE THREAD

**Issue by kba** [kba/awesome-ocr#88]
- existing datasets, c.f. https://github.com/cneud/ocr-gt/issues/1
- tools to create (archiscribe, glyph miner, ocr-gt-edit...)
- tools to evaluate

**Comment by cneud** [comment]
I moved the data from [ocr-gt](https://github.com/cneud/ocr-gt) [here](https://github.com/cneud/awesome-ocr/tree/gt) to initiate a new datasets category with ground truth resources (and eventually further subcategories). 

Tools to create/evaluate ground truth would imho better fit in a subcategory under the software category (as they [partially](https://github.com/kba/awesome-ocr#ocr-evaluation) already do).
