### ISSUE TITLE
ProGanSR [achieving super resolution in 1 second]

### ISSUE THREAD

**Issue by christophered** [kba/awesome-ocr#97]
1 second super-resolution, we are in the golden age.
http://igl.ethz.ch/projects/prosr/
https://github.com/fperazzi/proSR
https://www.youtube.com/watch?v=HvH0b9K_Iro

**Comment by kba** [comment]
Interesting but what problem does this solve in OCR?

**Comment by christophered** [comment]
Can be integrated into text-line extraction.
but i get you.
